{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "64bf0a2e-50d2-4f8d-9847-5af449d1c17c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Channels:\n",
      " - defaults\n",
      "Platform: linux-64\n",
      "Collecting package metadata (repodata.json): done\n",
      "Solving environment: failed\n",
      "\n",
      "PackagesNotFoundError: The following packages are not available from current channels:\n",
      "\n",
      "  - rdkit\n",
      "\n",
      "Current channels:\n",
      "\n",
      "  - defaults\n",
      "\n",
      "To search for alternate channels that may provide the conda package you're\n",
      "looking for, navigate to\n",
      "\n",
      "    https://anaconda.org\n",
      "\n",
      "and use the search bar at the top of the page.\n",
      "\n",
      "\n",
      "\n",
      "CondaError: Run 'conda init' before 'conda activate'\n",
      "\n",
      "/bin/bash: line 1: 2: No such file or directory\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: xlrd in /home/lcc.fiocruz/.local/lib/python3.10/site-packages (2.0.1)\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: openpyxl in /home/lcc.fiocruz/.local/lib/python3.10/site-packages (3.1.5)\n",
      "Requirement already satisfied: et-xmlfile in /home/lcc.fiocruz/.local/lib/python3.10/site-packages (from openpyxl) (1.1.0)\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: pandas in /home/lcc.fiocruz/.local/lib/python3.10/site-packages (2.2.2)\n",
      "Requirement already satisfied: numpy>=1.22.4 in /home/lcc.fiocruz/.local/lib/python3.10/site-packages (from pandas) (2.1.0)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.10/site-packages (from pandas) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in /home/lcc.fiocruz/.local/lib/python3.10/site-packages (from pandas) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in /home/lcc.fiocruz/.local/lib/python3.10/site-packages (from pandas) (2024.1)\n",
      "Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: rdkit-pypi in /home/lcc.fiocruz/.local/lib/python3.10/site-packages (2022.9.5)\n",
      "Requirement already satisfied: numpy in /home/lcc.fiocruz/.local/lib/python3.10/site-packages (from rdkit-pypi) (2.1.0)\n",
      "Requirement already satisfied: Pillow in /home/lcc.fiocruz/.local/lib/python3.10/site-packages (from rdkit-pypi) (10.4.0)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.1.0 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"/opt/conda/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/opt/conda/lib/python3.10/runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/opt/conda/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/opt/conda/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n",
      "    handle._run()\n",
      "  File \"/opt/conda/lib/python3.10/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3075, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3130, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3334, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3517, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1507/197657854.py\", line 20, in <module>\n",
      "    from rdkit import Chem #biblioteca usada para manipular e gerar moleculas 3d\n",
      "  File \"/home/lcc.fiocruz/.local/lib/python3.10/site-packages/rdkit/__init__.py\", line 23, in <module>\n",
      "    from rdkit.Chem.Draw import IPythonConsole\n",
      "  File \"/home/lcc.fiocruz/.local/lib/python3.10/site-packages/rdkit/Chem/__init__.py\", line 18, in <module>\n",
      "    from rdkit import DataStructs\n",
      "  File \"/home/lcc.fiocruz/.local/lib/python3.10/site-packages/rdkit/DataStructs/__init__.py\", line 13, in <module>\n",
      "    from rdkit.DataStructs import cDataStructs\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.1.0 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"/opt/conda/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/opt/conda/lib/python3.10/runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/opt/conda/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/opt/conda/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n",
      "    handle._run()\n",
      "  File \"/opt/conda/lib/python3.10/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3075, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3130, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3334, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3517, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1507/197657854.py\", line 20, in <module>\n",
      "    from rdkit import Chem #biblioteca usada para manipular e gerar moleculas 3d\n",
      "  File \"/home/lcc.fiocruz/.local/lib/python3.10/site-packages/rdkit/__init__.py\", line 23, in <module>\n",
      "    from rdkit.Chem.Draw import IPythonConsole\n",
      "  File \"/home/lcc.fiocruz/.local/lib/python3.10/site-packages/rdkit/Chem/__init__.py\", line 20, in <module>\n",
      "    from rdkit.Chem import rdchem\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.1.0 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"/opt/conda/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/opt/conda/lib/python3.10/runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/opt/conda/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/opt/conda/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n",
      "    handle._run()\n",
      "  File \"/opt/conda/lib/python3.10/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3075, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3130, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3334, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3517, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1507/197657854.py\", line 20, in <module>\n",
      "    from rdkit import Chem #biblioteca usada para manipular e gerar moleculas 3d\n",
      "  File \"/home/lcc.fiocruz/.local/lib/python3.10/site-packages/rdkit/__init__.py\", line 23, in <module>\n",
      "    from rdkit.Chem.Draw import IPythonConsole\n",
      "  File \"/home/lcc.fiocruz/.local/lib/python3.10/site-packages/rdkit/Chem/__init__.py\", line 24, in <module>\n",
      "    from rdkit.Chem.rdmolops import *\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.1.0 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"/opt/conda/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/opt/conda/lib/python3.10/runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/opt/conda/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/opt/conda/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n",
      "    handle._run()\n",
      "  File \"/opt/conda/lib/python3.10/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3075, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3130, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3334, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3517, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1507/197657854.py\", line 20, in <module>\n",
      "    from rdkit import Chem #biblioteca usada para manipular e gerar moleculas 3d\n",
      "  File \"/home/lcc.fiocruz/.local/lib/python3.10/site-packages/rdkit/__init__.py\", line 23, in <module>\n",
      "    from rdkit.Chem.Draw import IPythonConsole\n",
      "  File \"/home/lcc.fiocruz/.local/lib/python3.10/site-packages/rdkit/Chem/Draw/__init__.py\", line 20, in <module>\n",
      "    from rdkit.Chem import rdDepictor\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.1.0 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"/opt/conda/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/opt/conda/lib/python3.10/runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/opt/conda/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/opt/conda/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n",
      "    handle._run()\n",
      "  File \"/opt/conda/lib/python3.10/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3075, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3130, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3334, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3517, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1507/197657854.py\", line 21, in <module>\n",
      "    from rdkit.Chem import AllChem #biblioteca usada para manipular e gerar moleculas 3d\n",
      "  File \"/home/lcc.fiocruz/.local/lib/python3.10/site-packages/rdkit/Chem/AllChem.py\", line 27, in <module>\n",
      "    from rdkit.Chem.rdDistGeom import *\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.1.0 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"/opt/conda/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/opt/conda/lib/python3.10/runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/opt/conda/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/opt/conda/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n",
      "    handle._run()\n",
      "  File \"/opt/conda/lib/python3.10/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3075, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3130, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3334, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3517, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1507/197657854.py\", line 21, in <module>\n",
      "    from rdkit.Chem import AllChem #biblioteca usada para manipular e gerar moleculas 3d\n",
      "  File \"/home/lcc.fiocruz/.local/lib/python3.10/site-packages/rdkit/Chem/AllChem.py\", line 29, in <module>\n",
      "    from rdkit.Chem.rdMolAlign import *\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.1.0 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"/opt/conda/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/opt/conda/lib/python3.10/runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/opt/conda/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/opt/conda/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n",
      "    handle._run()\n",
      "  File \"/opt/conda/lib/python3.10/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3075, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3130, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3334, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3517, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1507/197657854.py\", line 21, in <module>\n",
      "    from rdkit.Chem import AllChem #biblioteca usada para manipular e gerar moleculas 3d\n",
      "  File \"/home/lcc.fiocruz/.local/lib/python3.10/site-packages/rdkit/Chem/AllChem.py\", line 31, in <module>\n",
      "    from rdkit.Chem.rdMolTransforms import *\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.1.0 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"/opt/conda/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/opt/conda/lib/python3.10/runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/opt/conda/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/opt/conda/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n",
      "    handle._run()\n",
      "  File \"/opt/conda/lib/python3.10/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3075, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3130, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3334, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3517, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1507/197657854.py\", line 21, in <module>\n",
      "    from rdkit.Chem import AllChem #biblioteca usada para manipular e gerar moleculas 3d\n",
      "  File \"/home/lcc.fiocruz/.local/lib/python3.10/site-packages/rdkit/Chem/AllChem.py\", line 33, in <module>\n",
      "    from rdkit.Chem.rdReducedGraphs import *\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.1.0 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"/opt/conda/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/opt/conda/lib/python3.10/runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/opt/conda/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/opt/conda/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n",
      "    handle._run()\n",
      "  File \"/opt/conda/lib/python3.10/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3075, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3130, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3334, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3517, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1507/197657854.py\", line 21, in <module>\n",
      "    from rdkit.Chem import AllChem #biblioteca usada para manipular e gerar moleculas 3d\n",
      "  File \"/home/lcc.fiocruz/.local/lib/python3.10/site-packages/rdkit/Chem/AllChem.py\", line 34, in <module>\n",
      "    from rdkit.Chem.rdShapeHelpers import *\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "--2024-08-21 17:55:41--  https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.2-Linux-x86_64.sh\n",
      "Resolving repo.anaconda.com (repo.anaconda.com)... 104.16.191.158, 104.16.32.241, 2606:4700::6810:bf9e, ...\n",
      "Connecting to repo.anaconda.com (repo.anaconda.com)|104.16.191.158|:443... connected.\n",
      "HTTP request sent, awaiting response... 200 OK\n",
      "Length: 85055499 (81M) [application/x-sh]\n",
      "Saving to: ‘Miniconda3-py37_4.8.2-Linux-x86_64.sh.9’\n",
      "\n",
      "Miniconda3-py37_4.8 100%[===================>]  81.12M  11.2MB/s    in 7.6s    \n",
      "\n",
      "2024-08-21 17:55:49 (10.7 MB/s) - ‘Miniconda3-py37_4.8.2-Linux-x86_64.sh.9’ saved [85055499/85055499]\n",
      "\n",
      "PREFIX=/usr/local\n",
      "./Miniconda3-py37_4.8.2-Linux-x86_64.sh: line 392: /usr/local/conda.exe: Permission denied\n",
      "chmod: cannot access '/usr/local/conda.exe': No such file or directory\n",
      "Unpacking payload ...\n",
      "./Miniconda3-py37_4.8.2-Linux-x86_64.sh: line 404: /usr/local/conda.exe: No such file or directory\n",
      "./Miniconda3-py37_4.8.2-Linux-x86_64.sh: line 406: /usr/local/conda.exe: No such file or directory\n",
      "Channels:\n",
      " - conda-forge\n",
      " - defaults\n",
      "Platform: linux-64\n",
      "Collecting package metadata (repodata.json): ...working... done\n",
      "Solving environment: ...working... done\n",
      "\n",
      "## Package Plan ##\n",
      "\n",
      "  environment location: /opt/conda\n",
      "\n",
      "  added / updated specs:\n",
      "    - openbabel\n",
      "\n",
      "\n",
      "The following NEW packages will be INSTALLED:\n",
      "\n",
      "  cairo              conda-forge/linux-64::cairo-1.18.0-hebfffa5_3 \n",
      "  font-ttf-dejavu-s~ conda-forge/noarch::font-ttf-dejavu-sans-mono-2.37-hab24e00_0 \n",
      "  font-ttf-inconsol~ conda-forge/noarch::font-ttf-inconsolata-3.000-h77eed37_0 \n",
      "  font-ttf-source-c~ conda-forge/noarch::font-ttf-source-code-pro-2.038-h77eed37_0 \n",
      "  font-ttf-ubuntu    conda-forge/noarch::font-ttf-ubuntu-0.83-h77eed37_2 \n",
      "  fontconfig         conda-forge/linux-64::fontconfig-2.14.2-h14ed4e7_0 \n",
      "  fonts-conda-ecosy~ conda-forge/noarch::fonts-conda-ecosystem-1-0 \n",
      "  fonts-conda-forge  conda-forge/noarch::fonts-conda-forge-1-0 \n",
      "  freetype           conda-forge/linux-64::freetype-2.12.1-h267a509_2 \n",
      "  libglib            conda-forge/linux-64::libglib-2.80.3-h315aac3_2 \n",
      "  libiconv           conda-forge/linux-64::libiconv-1.17-hd590300_2 \n",
      "  libnsl             conda-forge/linux-64::libnsl-2.0.1-hd590300_0 \n",
      "  libpng             conda-forge/linux-64::libpng-1.6.43-h2797004_0 \n",
      "  libsqlite          conda-forge/linux-64::libsqlite-3.45.2-h2797004_0 \n",
      "  libxcb             conda-forge/linux-64::libxcb-1.16-hd590300_0 \n",
      "  libxcrypt          conda-forge/linux-64::libxcrypt-4.4.36-hd590300_1 \n",
      "  libzlib            conda-forge/linux-64::libzlib-1.3.1-h4ab18f5_1 \n",
      "  lzo                conda-forge/linux-64::lzo-2.10-hd590300_1001 \n",
      "  openbabel          conda-forge/linux-64::openbabel-3.1.1-py310hbff9852_9 \n",
      "  pixman             conda-forge/linux-64::pixman-0.43.2-h59595ed_0 \n",
      "  pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-h36c2ea0_1001 \n",
      "  python_abi         conda-forge/linux-64::python_abi-3.10-5_cp310 \n",
      "  xorg-kbproto       conda-forge/linux-64::xorg-kbproto-1.0.7-h7f98852_1002 \n",
      "  xorg-libice        conda-forge/linux-64::xorg-libice-1.1.1-hd590300_0 \n",
      "  xorg-libsm         conda-forge/linux-64::xorg-libsm-1.2.4-h7391055_0 \n",
      "  xorg-libx11        conda-forge/linux-64::xorg-libx11-1.8.9-hb711507_1 \n",
      "  xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.11-hd590300_0 \n",
      "  xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.3-h7f98852_0 \n",
      "  xorg-libxext       conda-forge/linux-64::xorg-libxext-1.3.4-h0b41bf4_2 \n",
      "  xorg-libxrender    conda-forge/linux-64::xorg-libxrender-0.9.11-hd590300_0 \n",
      "  xorg-renderproto   conda-forge/linux-64::xorg-renderproto-0.11.1-h7f98852_1002 \n",
      "  xorg-xextproto     conda-forge/linux-64::xorg-xextproto-7.3.0-h0b41bf4_1003 \n",
      "  xorg-xproto        conda-forge/linux-64::xorg-xproto-7.0.31-h7f98852_1007 \n",
      "\n",
      "The following packages will be UPDATED:\n",
      "\n",
      "  ca-certificates    pkgs/main::ca-certificates-2024.7.2-h~ --> conda-forge::ca-certificates-2024.7.4-hbcca054_0 \n",
      "  icu                        pkgs/main::icu-73.1-h6a678d5_0 --> conda-forge::icu-75.1-he02047a_0 \n",
      "  libgcc-ng          pkgs/main::libgcc-ng-11.2.0-h1234567_1 --> conda-forge::libgcc-ng-14.1.0-h77fa898_0 \n",
      "  libgomp              pkgs/main::libgomp-11.2.0-h1234567_1 --> conda-forge::libgomp-14.1.0-h77fa898_0 \n",
      "  libsolv              pkgs/main::libsolv-0.7.24-he621ea3_1 --> conda-forge::libsolv-0.7.30-h3509ff9_0 \n",
      "  libstdcxx-ng       pkgs/main::libstdcxx-ng-11.2.0-h12345~ --> conda-forge::libstdcxx-ng-14.1.0-hc0a3c3a_0 \n",
      "  libuuid              pkgs/main::libuuid-1.41.5-h5eee18b_0 --> conda-forge::libuuid-2.38.1-h0b41bf4_0 \n",
      "  libxml2              pkgs/main::libxml2-2.10.4-hfdd30dd_2 --> conda-forge::libxml2-2.12.7-he7c6b58_4 \n",
      "  openssl              pkgs/main::openssl-3.0.14-h5eee18b_0 --> conda-forge::openssl-3.3.1-h4bc722e_2 \n",
      "  pcre2                   pkgs/main::pcre2-10.42-hebb0a14_1 --> conda-forge::pcre2-10.44-hba22ea6_2 \n",
      "  zlib                    pkgs/main::zlib-1.2.13-h5eee18b_1 --> conda-forge::zlib-1.3.1-h4ab18f5_1 \n",
      "\n",
      "The following packages will be SUPERSEDED by a higher-priority channel:\n",
      "\n",
      "  _libgcc_mutex           pkgs/main::_libgcc_mutex-0.1-main --> conda-forge::_libgcc_mutex-0.1-conda_forge \n",
      "  _openmp_mutex          pkgs/main::_openmp_mutex-5.1-1_gnu --> conda-forge::_openmp_mutex-4.5-2_gnu \n",
      "  certifi            pkgs/main/linux-64::certifi-2024.7.4-~ --> conda-forge/noarch::certifi-2024.7.4-pyhd8ed1ab_0 \n",
      "  conda              pkgs/main::conda-24.7.1-py310h06a4308~ --> conda-forge::conda-24.7.1-py310hff52083_0 \n",
      "  libarchive         pkgs/main::libarchive-3.6.2-h6ac8c49_3 --> conda-forge::libarchive-3.6.2-h039dbb9_1 \n",
      "  libcurl               pkgs/main::libcurl-8.7.1-h251f7ec_0 --> conda-forge::libcurl-8.1.2-h409715c_0 \n",
      "  libnghttp2         pkgs/main::libnghttp2-1.57.0-h2d74bed~ --> conda-forge::libnghttp2-1.52.0-h61bc06f_0 \n",
      "  libssh2              pkgs/main::libssh2-1.11.0-h251f7ec_0 --> conda-forge::libssh2-1.11.0-h0841786_0 \n",
      "  python               pkgs/main::python-3.10.14-h955ad1f_1 --> conda-forge::python-3.10.13-hd12c33a_1_cpython \n",
      "  sqlite                pkgs/main::sqlite-3.45.3-h5eee18b_0 --> conda-forge::sqlite-3.45.2-h2c6b66d_0 \n",
      "  tk                        pkgs/main::tk-8.6.14-h39e8969_0 --> conda-forge::tk-8.6.13-noxft_h4845f30_101 \n",
      "  zstd                     pkgs/main::zstd-1.5.5-hc292b87_2 --> conda-forge::zstd-1.5.5-hfc55251_0 \n",
      "\n",
      "\n",
      "Preparing transaction: ...working... done\n",
      "Verifying transaction: ...working... failed\n",
      "\n",
      "EnvironmentNotWritableError: The current user does not have write permissions to the target environment.\n",
      "  environment location: /opt/conda\n",
      "  uid: 1001\n",
      "  gid: 1001\n",
      "\n",
      "\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: py3Dmol in /home/lcc.fiocruz/.local/lib/python3.10/site-packages (2.3.0)\n",
      "--2024-08-21 17:56:15--  https://downloads.sourceforge.net/project/smina/smina.static\n",
      "Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 204.68.111.105\n",
      "Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|204.68.111.105|:443... connected.\n",
      "HTTP request sent, awaiting response... 302 Found\n",
      "Location: https://versaweb.dl.sourceforge.net/project/smina/smina.static?viasf=1 [following]\n",
      "--2024-08-21 17:56:16--  https://versaweb.dl.sourceforge.net/project/smina/smina.static?viasf=1\n",
      "Resolving versaweb.dl.sourceforge.net (versaweb.dl.sourceforge.net)... 162.251.232.173\n",
      "Connecting to versaweb.dl.sourceforge.net (versaweb.dl.sourceforge.net)|162.251.232.173|:443... connected.\n",
      "HTTP request sent, awaiting response... 200 OK\n",
      "Length: 9853920 (9.4M) [application/octet-stream]\n",
      "Saving to: ‘smina.static.8’\n",
      "\n",
      "smina.static.8      100%[===================>]   9.40M  5.36MB/s    in 1.8s    \n",
      "\n",
      "2024-08-21 17:56:18 (5.36 MB/s) - ‘smina.static.8’ saved [9853920/9853920]\n",
      "\n",
      "--2024-08-21 17:56:18--  https://github.com/gnina/gnina/releases/download/v1.0.1/gnina\n",
      "Resolving github.com (github.com)... 140.82.113.4\n",
      "Connecting to github.com (github.com)|140.82.113.4|:443... connected.\n",
      "HTTP request sent, awaiting response... 302 Found\n",
      "Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/45548146/47de2300-8bd4-11eb-8355-430c51e07fae?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240821%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240821T175618Z&X-Amz-Expires=300&X-Amz-Signature=a71afa3c823449fcfee870534595027df518a0482752b5ef7d07b7f4062bb39d&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=45548146&response-content-disposition=attachment%3B%20filename%3Dgnina&response-content-type=application%2Foctet-stream [following]\n",
      "--2024-08-21 17:56:18--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/45548146/47de2300-8bd4-11eb-8355-430c51e07fae?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240821%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240821T175618Z&X-Amz-Expires=300&X-Amz-Signature=a71afa3c823449fcfee870534595027df518a0482752b5ef7d07b7f4062bb39d&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=45548146&response-content-disposition=attachment%3B%20filename%3Dgnina&response-content-type=application%2Foctet-stream\n",
      "Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.110.133, ...\n",
      "Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.108.133|:443... connected.\n",
      "HTTP request sent, awaiting response... 200 OK\n",
      "Length: 562802104 (537M) [application/octet-stream]\n",
      "Saving to: ‘gnina.5’\n",
      "\n",
      "gnina.5             100%[===================>] 536.73M  10.4MB/s    in 51s     \n",
      "\n",
      "2024-08-21 17:57:10 (10.5 MB/s) - ‘gnina.5’ saved [562802104/562802104]\n",
      "\n"
     ]
    }
   ],
   "source": [
    "#######################################################################################################################################\n",
    "######### CRIADO POR      :  MIRIAM OLIVEIRA, LAURO MIRANDA E RAFAEL OLIVEIRA                                                 #########\n",
    "######### CÓDIGO ADAPTADO :  https://colab.research.google.com/drive/1GXmk1v8C-c4UtyKFqIm9HnsrVYH0pI-c                        #########\n",
    "######### OBJETIVO      :  EFETUAR A LEITURA DE UMA LISTA DE LIGANTES QUE SERÃO TESTADOS PARA O RECEPTOR 5U1L                 #########\n",
    "#########                  UTILIZANDO A BIBLIOTECA GNINA. OS DADOS SALVOS SERÃO EXPORTADOS PARA UM ARQUIVO DE SAÍDA           #########\n",
    "######### DATA          :  24/08/2021                                                                                         #########\n",
    "######### ARQUIVO DE ENTRADA : LIGANTES.XLSX       (CLICAR COM O BOTÃO DIREITO EM FILES E FAZER UPLOAD DESTE ARQUIVO)         #########\n",
    "######### ARQUIVO DE SAÍDA   : GNINA_SCORE_RECEPTOR_LIGANTES.csv  (SERÁ SALVO AUTOMATICAMENTE E DISPONIBLIZADO POR DOWNLOAD) #########\n",
    "###############################################################################################################V#######################\n",
    "!conda create -n myenv python=3.10 numpy=1.21 rdkit\n",
    "!conda activate myenv\n",
    "!pip install numpy<2\n",
    "!pip install xlrd\n",
    "!pip install openpyxl\n",
    "!pip install pandas\n",
    "!pip install rdkit-pypi #biblioteca usada para manipular e gerar moleculas 3d\n",
    "import xlrd           #biblioteca usada para manipular arquivo excell\n",
    "import pandas as pd   #biblioteca usada para ler os resultados\n",
    "import subprocess, io, re  #bibliotecas para extração dos resultados do arquivo txt por palavras chave (que contém o score)\n",
    "from rdkit import Chem #biblioteca usada para manipular e gerar moleculas 3d\n",
    "from rdkit.Chem import AllChem #biblioteca usada para manipular e gerar moleculas 3d\n",
    "import os\n",
    "\n",
    "################################################################################\n",
    "# INSTALL CONDA ON GOOGLE COLAB\n",
    "################################################################################\n",
    "! wget https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.2-Linux-x86_64.sh\n",
    "! chmod +x Miniconda3-py37_4.8.2-Linux-x86_64.sh\n",
    "! bash ./Miniconda3-py37_4.8.2-Linux-x86_64.sh -b -f -p /usr/local\n",
    "\n",
    "! conda install -q -y -c conda-forge openbabel\n",
    "\n",
    "import sys\n",
    "sys.path.append('/usr/local/lib/python3.7/site-packages/')\n",
    "\n",
    "!pip install py3Dmol\n",
    "\n",
    "!wget https://downloads.sourceforge.net/project/smina/smina.static\n",
    "\n",
    "!wget https://github.com/gnina/gnina/releases/download/v1.0.1/gnina\n",
    "\n",
    "!chmod +x gnina\n",
    "\n",
    "!./gnina\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "15681678-fb5a-4af6-b6c8-d1f489726f8f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "TOTAL DE LIGANTES: 100\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "#LEITURA DO ARQUIVO LIGANTES.XLSX  (MUDE O NOME DO ARQUIVO NESTE PONTO!)\n",
    "\n",
    "ArqListaLigantes='./Planilha_Ambinter.xls'  # para executar tudo de uma vez\n",
    "\n",
    "# Altere o 0 para a linha onde os dados começam a ser exibidos\n",
    "tabela = xlrd.open_workbook(ArqListaLigantes).sheet_by_index(0)\n",
    "qtd_linhas = tabela.nrows\n",
    "\n",
    "print(\"TOTAL DE LIGANTES: \" + str(qtd_linhas))\n",
    "print(\"\\n\")\n",
    "\n",
    "data = []"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "eee10858-5cc1-4e21-bf07-b91b8b205a4a",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "36f468ab-8d65-44f5-b974-ae369680e3e4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "=======================================INÍCIO DO PROCESSAMENTO===========================================\n",
      "\n",
      "GRUPO: Amb10069245\n",
      "MOLECULA: ZINC000001690027\n",
      "SMILE: CC(=O)c1cccc(C)n1\n",
      "\n",
      "Moléculas restantes: 99\n",
      "=======================================INÍCIO DO PROCESSAMENTO===========================================\n",
      "\n",
      "GRUPO: Amb10069355\n",
      "MOLECULA: ZINC000001549593\n",
      "SMILE: O=C(O)[C@H](O)[C@H](O)[C@@H](O)[C@@H](O)C(=O)O\n",
      "\n",
      "Moléculas restantes: 98\n",
      "=======================================INÍCIO DO PROCESSAMENTO===========================================\n",
      "\n",
      "GRUPO: Amb10069355\n",
      "MOLECULA: ZINC000003581021\n",
      "SMILE: O=C(O)[C@H](O)[C@@H](O)[C@@H](O)[C@@H](O)C(=O)O\n",
      "\n",
      "Moléculas restantes: 97\n",
      "=======================================INÍCIO DO PROCESSAMENTO===========================================\n",
      "\n",
      "GRUPO: Amb10069355\n",
      "MOLECULA: ZINC000006072527\n",
      "SMILE: O=C(O)[C@@H](O)[C@@H](O)[C@@H](O)[C@@H](O)C(=O)O\n",
      "\n",
      "Moléculas restantes: 96\n",
      "=======================================INÍCIO DO PROCESSAMENTO===========================================\n",
      "\n",
      "GRUPO: Amb10069355\n",
      "MOLECULA: ZINC000013533920\n",
      "SMILE: O=C(O)[C@@H](O)[C@H](O)[C@@H](O)[C@@H](O)C(=O)O\n",
      "\n",
      "Moléculas restantes: 95\n",
      "=======================================INÍCIO DO PROCESSAMENTO===========================================\n",
      "\n",
      "GRUPO: Amb10069624\n",
      "MOLECULA: ZINC000000967521\n",
      "SMILE: CC1(C)[C@H]2CC[C@]1(C)C(=O)C2\n",
      "\n",
      "Moléculas restantes: 94\n",
      "=======================================INÍCIO DO PROCESSAMENTO===========================================\n",
      "\n",
      "GRUPO: Amb10069843\n",
      "MOLECULA: ZINC000000105216\n",
      "SMILE: COc1ccc2cc([C@H](C)C(=O)O)ccc2c1\n",
      "\n",
      "Moléculas restantes: 93\n",
      "=======================================INÍCIO DO PROCESSAMENTO===========================================\n",
      "\n",
      "GRUPO: Amb10069843\n",
      "MOLECULA: ZINC000000113439\n",
      "SMILE: COc1ccc2cc([C@@H](C)C(=O)O)ccc2c1\n",
      "\n",
      "Moléculas restantes: 92\n",
      "=======================================INÍCIO DO PROCESSAMENTO===========================================\n",
      "\n",
      "GRUPO: Amb10070600\n",
      "MOLECULA: ZINC000000625862\n",
      "SMILE: COc1cc([C@@H]2c3cc4c(cc3[C@H](O)[C@H]3COC(=O)[C@@H]23)OCO4)cc(OC)c1O\n",
      "\n",
      "Moléculas restantes: 91\n",
      "=======================================INÍCIO DO PROCESSAMENTO===========================================\n",
      "\n",
      "GRUPO: Amb10070600\n",
      "MOLECULA: ZINC000004098756\n",
      "SMILE: COc1cc([C@@H]2c3cc4c(cc3[C@H](O)[C@H]3COC(=O)[C@H]23)OCO4)cc(OC)c1O\n",
      "\n",
      "Moléculas restantes: 90\n",
      "=======================================INÍCIO DO PROCESSAMENTO===========================================\n",
      "\n",
      "GRUPO: Amb10070600\n",
      "MOLECULA: ZINC000013783532\n",
      "SMILE: COc1cc([C@@H]2c3cc4c(cc3[C@H](O)[C@@H]3COC(=O)[C@@H]32)OCO4)cc(OC)c1O\n",
      "\n",
      "Moléculas restantes: 89\n",
      "=======================================INÍCIO DO PROCESSAMENTO===========================================\n",
      "\n",
      "GRUPO: Amb10070600\n",
      "MOLECULA: ZINC000013783534\n",
      "SMILE: COc1cc([C@@H]2c3cc4c(cc3[C@H](O)[C@@H]3COC(=O)[C@H]32)OCO4)cc(OC)c1O\n",
      "\n",
      "Moléculas restantes: 88\n",
      "=======================================INÍCIO DO PROCESSAMENTO===========================================\n",
      "\n",
      "GRUPO: Amb10071534\n",
      "MOLECULA: ZINC000006007189\n",
      "SMILE: COc1ccc(/C=C\\C(=O)O)cc1OC\n",
      "\n",
      "Moléculas restantes: 87\n",
      "=======================================INÍCIO DO PROCESSAMENTO===========================================\n",
      "\n",
      "GRUPO: Amb10071969\n",
      "MOLECULA: ZINC000005158137\n",
      "SMILE: C=C[C@@](C)(O)C/C=C/C(=C)C\n",
      "\n",
      "Moléculas restantes: 86\n",
      "=======================================INÍCIO DO PROCESSAMENTO===========================================\n",
      "\n",
      "GRUPO: Amb10071969\n",
      "MOLECULA: ZINC000005158140\n",
      "SMILE: C=C[C@](C)(O)C/C=C/C(=C)C\n",
      "\n",
      "Moléculas restantes: 85\n",
      "=======================================INÍCIO DO PROCESSAMENTO===========================================\n",
      "\n",
      "GRUPO: Amb10241330\n",
      "MOLECULA: ZINC000118912415\n",
      "SMILE: COC(=O)CC[C@H](C)[C@H]1CC[C@H]2[C@H]3[C@H](C[C@@H](O)[C@@]21C)[C@@]1(C)CC[C@H](O)C[C@@H]1C[C@H]3O\n",
      "\n",
      "Moléculas restantes: 84\n",
      "=======================================INÍCIO DO PROCESSAMENTO===========================================\n",
      "\n",
      "GRUPO: Amb10241330\n",
      "MOLECULA: ZINC000118912416\n",
      "SMILE: COC(=O)CC[C@@H](C)[C@H]1CC[C@H]2[C@H]3[C@H](C[C@@H](O)[C@@]21C)[C@@]1(C)CC[C@H](O)C[C@@H]1C[C@H]3O\n",
      "\n",
      "Moléculas restantes: 83\n",
      "=======================================INÍCIO DO PROCESSAMENTO===========================================\n",
      "\n",
      "GRUPO: Amb10241330\n",
      "MOLECULA: ZINC001903846772\n",
      "SMILE: COC(=O)CC[C@H](C)[C@@H]1CC[C@H]2[C@H]3[C@H](C[C@@H](O)[C@]12C)[C@@]1(C)CC[C@H](O)C[C@@H]1C[C@H]3O\n",
      "\n",
      "Moléculas restantes: 82\n",
      "=======================================INÍCIO DO PROCESSAMENTO===========================================\n",
      "\n",
      "GRUPO: Amb10241330\n",
      "MOLECULA: ZINC001903846773\n",
      "SMILE: COC(=O)CC[C@@H](C)[C@@H]1CC[C@H]2[C@H]3[C@H](C[C@@H](O)[C@]12C)[C@@]1(C)CC[C@H](O)C[C@@H]1C[C@H]3O\n",
      "\n",
      "Moléculas restantes: 81\n",
      "=======================================INÍCIO DO PROCESSAMENTO===========================================\n",
      "\n",
      "GRUPO: Amb1028975\n",
      "MOLECULA: ZINC000000714631\n",
      "SMILE: COc1ccc(/C=C/C(=O)NCCc2ccc(OC)c(OC)c2)cc1OC\n",
      "\n",
      "Moléculas restantes: 80\n",
      "=======================================INÍCIO DO PROCESSAMENTO===========================================\n",
      "\n",
      "GRUPO: Amb1033014\n",
      "MOLECULA: ZINC000000052601\n",
      "SMILE: CC(=O)CCc1ccc2c(c1)OCO2\n",
      "\n",
      "Moléculas restantes: 79\n",
      "=======================================INÍCIO DO PROCESSAMENTO===========================================\n",
      "\n",
      "GRUPO: Amb1033145\n",
      "MOLECULA: ZINC000245226046\n",
      "SMILE: CN1[C@H]2CC[C@H]1CC(OC(=O)[C@H]1CC[C@](C(=O)OC3C[C@@H]4CC[C@H](C3)N4C)(c3ccccc3)c3ccccc31)C2\n",
      "\n",
      "Erro ao processar a molécula ZINC000245226046: Bad Conformer Id\n",
      "Moléculas restantes: 78\n",
      "=======================================INÍCIO DO PROCESSAMENTO===========================================\n",
      "\n",
      "GRUPO: Amb1033145\n",
      "MOLECULA: ZINC000245226047\n",
      "SMILE: CN1[C@H]2CC[C@H]1CC(OC(=O)[C@H]1CC[C@@](C(=O)OC3C[C@@H]4CC[C@H](C3)N4C)(c3ccccc3)c3ccccc31)C2\n",
      "\n",
      "Erro ao processar a molécula ZINC000245226047: Bad Conformer Id\n",
      "Moléculas restantes: 77\n",
      "=======================================INÍCIO DO PROCESSAMENTO===========================================\n",
      "\n",
      "GRUPO: Amb1033145\n",
      "MOLECULA: ZINC000245226048\n",
      "SMILE: CN1[C@H]2CC[C@H]1CC(OC(=O)[C@@H]1CC[C@@](C(=O)OC3C[C@@H]4CC[C@H](C3)N4C)(c3ccccc3)c3ccccc31)C2\n",
      "\n"
     ]
    }
   ],
   "source": [
    "data = []\n",
    "\n",
    "try:\n",
    "    total_molecules = qtd_linhas  # Total de moléculas a serem processadas\n",
    "\n",
    "    for linha in range(0, total_molecules):\n",
    "        try:\n",
    "            # Ler as colunas da tabela\n",
    "            grupoMolecula = tabela.row(linha)[0].value.strip()  # Ler coluna GRUPO\n",
    "            nomeMolecula = tabela.row(linha)[1].value.strip()  # Ler coluna MOLECULA\n",
    "            smileMolecula = tabela.row(linha)[2].value.strip()  # Ler coluna SMILE\n",
    "\n",
    "            print(\"=======================================INÍCIO DO PROCESSAMENTO===========================================\")\n",
    "            print(f\"\\nGRUPO: {grupoMolecula}\\nMOLECULA: {nomeMolecula}\\nSMILE: {smileMolecula}\\n\")\n",
    "\n",
    "            # Gravar arquivo SMILE\n",
    "            with open(\"smile.txt\", \"w\") as arquivo:\n",
    "                arquivo.write(smileMolecula)\n",
    "\n",
    "            # Converter SMILES para objeto de molécula RDKit\n",
    "            molecule = Chem.MolFromSmiles(smileMolecula)\n",
    "            molecule = Chem.AddHs(molecule)\n",
    "            AllChem.EmbedMolecule(molecule, AllChem.ETKDG())\n",
    "            AllChem.UFFOptimizeMolecule(molecule, maxIters=100)\n",
    "            with open('molecule.sdf', 'a') as f:\n",
    "                f.write(Chem.MolToMolBlock(molecule))\n",
    "\n",
    "            # Executar GNINA\n",
    "            os.system('./gnina -r ./Maestro_hp2x7p_alphafold_trimerico.pdb -l molecule.sdf --center_x -7.218 --center_y -44.877 --center_z -2.503 --size_x 50 --size_y 40 --size_z 40 --seed -1985 > scores.txt 2>&1')\n",
    "\n",
    "            # Ler e processar os resultados\n",
    "            with open(\"scores.txt\", \"r\") as file:\n",
    "                lines = file.readlines()\n",
    "            for line in lines:\n",
    "                line = line.strip()\n",
    "                if re.match(r\"\\s*\\d+\\s+[-+]?\\d+\\.\\d+\\s+[-+]?\\d+\\.\\d+\\s+[-+]?\\d+\\.\\d+\", line):\n",
    "                    columns = line.split()\n",
    "                    mode = int(columns[0])\n",
    "                    affinity = float(columns[1])\n",
    "                    cnn_score = float(columns[2])\n",
    "                    cnn_affinity = float(columns[3])\n",
    "                    data.append((mode, affinity, cnn_score, cnn_affinity, \"Success\", smileMolecula, grupoMolecula, nomeMolecula))\n",
    "\n",
    "        except Exception as e:\n",
    "            print(f\"Erro ao processar a molécula {nomeMolecula}: {e}\")\n",
    "            data.append((\"N/A\", \"N/A\", \"N/A\", \"N/A\", \"Error\", smileMolecula, grupoMolecula, nomeMolecula))\n",
    "\n",
    "        # Imprime quantas moléculas faltam\n",
    "        remaining_molecules = total_molecules - (linha + 1)\n",
    "        print(f\"Moléculas restantes: {remaining_molecules}\")\n",
    "\n",
    "except Exception as e:\n",
    "    print(f\"Erro geral: {e}\")\n",
    "\n",
    "# Converter os dados em um DataFrame\n",
    "scores_df = pd.DataFrame(data, columns=['Mode', 'Affinity', 'CNN Score', 'CNN Affinity', 'Status', \"Smile\", \"Molecule Group\", \"Molecule Name\"])\n",
    "\n",
    "# Converter DataFrame em Excel\n",
    "scores_df.to_excel('scores.xlsx', index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b0c5f228-930e-40e3-a733-31a3360d576e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Converte scores em DataFrame\n",
    "scores_df = pd.DataFrame(data, columns=['Mode', 'Affinity', 'CNN Score', 'CNN Affinity', 'Status', \"Smile\", \"Molecule Group\", \"Molecule Name\"])\n",
    "\n",
    "scores_df\n",
    "\n",
    "# Converte DataFrame em Excel\n",
    "scores_df.to_excel('scores.xlsx', index=False)\n",
    "\n",
    "# Baixa Excel\n",
    "files.download('scores.xlsx')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bee58b88-1125-4e14-8677-ee6236857276",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.14"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
